### ISSUE TITLE
Thermal conductivity for thermochemical nonequilibrium

### ISSUE THREAD

**Issue by CatarinaGarbacz** [mutationpp/Mutationpp#107]
Hi all.
I am linking Mutation++ to a CFD solver considering thermal and chemical nonequilibrium. When it comes to computing transport properties from Mutation++, I have some questions on how to treat thermal conductivity.

In Transport.h, there is no function to compute thermal conductivity that explicitly refers to a reactive flow with 2 temperatures. 

My first approach would be to use function frozenThermalConductivityVector. Although the function is described as " Returns the mixture thermal conductivity vector for a frozen mixture according to the state model", as far as I know (which is not that much), there is no coupling with chemistry in the calculation of this property. So my guess is that, even with chemistry going on,  for each point in the mesh we have fixed mass fractions and with that we would update the mixture state and call the corresponding frozenThermalConductivityVector.

I am however not entirely sure about this and would like to have some feedback, to know if this is correct or if there is another way of treating the problem. 

Thanks

**Comment by jbscoggi** [comment]
Hey @CatarinaGarbacz, yes you are correct that the frozenThermalConductivityVector is the correct function to call.  "Frozen" in this case refers to the opposite of equilibrium, just meaning that the species composition is not a function of temperature or pressure.  When this is the case, as in chemical equilibrium conditions, then an additional term called the "reactive thermal conductivity" must be included which takes into account the change in species mole fractions due to a change in temperature.  Of course this terminology is very misleading I know, but I didn't make it up!

**Comment by CatarinaGarbacz** [comment]
Very clear JB, thank you!

**Comment by jbscoggi** [comment]
Thanks! :)
