### ISSUE TITLE
Documentation for using bprime?

### ISSUE THREAD

**Issue by kbibbles** [mutationpp/Mutationpp#135]
Hello,

I downloaded m++ from github and built successfully on my local system. However, I can't build the documentation (nothing happens when I run make docs - yes I have doxygen installed). It is not clear to me how to use the bprime executable, in particular: what format and information should the BLedge and pyrolysis gas inputs contain? Should they be in xml format like the mixture composition input? Should they include mass fractions for specific conditions, or only elemental compositions?

Thanks!

Kyle

**Comment by jbscoggi** [comment]
Hi @kbibbles, let me split the question in 2 parts:

1. `make docs` not working

Make docs should only be available as a build target once you have successfully configured using cmake.  If you try to call this before running cmake in the [build step](https://github.com/mutationpp/Mutationpp/blob/master/docs/installation.md#build), the make target will not exist.  In addition, you will probably need to turn ON the ability to make the docs.  This requires a slightly more complicated cmake step.  Start by running `cmake ..` from your build directory.  This will bring up an interactive screen where you can select options.  Make sure that the `BUILD_DOCUMENTATION` option is ON by using the arrow key to move to that option and the Enter key to select it.  Once it is ON, you can type `c`, `c`, `g`.  This will configure the new makefile and generate it.  Now `make docs` should work.

2. How to use `bprime` tool

Yes, it is not super clear from the documentation.  Sorry for that.  The -bl and -py options are the names of the associated elemental compositions in the mixture file which represent the compositions for the boundary layer edge and the pyrolysis gas, respectively.  For example, if you take a look at the mixture file for TACOT (`data/mixtures/tacot-air_35.xml`) you will see the elemental composition definition:

```xml
<element_compositions default="phenol-air">
    <composition name="phenol-air">C:6, H:6, O:1.4, N:1.6</composition>
</element_compositions>
```

As you can see, there is a single composition named here, called "phenol-air" which represents a phenol-air mixture.  The format is a comma-separated list of element/stoichiometry values.  The default is in terms of moles and the values will all be normalized to sum to one, so that they represent mole fractions.  To specify mass fractions instead, simply add the attribute `type="mass"`.  You can add your own compositions.  For example if you had

```xml
<element_compositions default="phenol-air">
    <composition name="phenol-air">C:6, H:6, O:1.4, N:1.6</composition>
    <composition name="phenol">C:6, H:6, O:1</composition>
    <composition name="air">N:0.79, O:0.21</composition>
</element_compositions>
```

Then you can call `bprime` with the `-bl air -py phenol` options, which would point to the named compositions in the mixture file.

I hope that helps, let me know if something is still not clear.

**Comment by jbscoggi** [comment]
Hi @kbibbles, were you able get the docs and bprime to work for you?  If so, I will go ahead and close the issue.

**Comment by kbibbles** [comment]
Yes, based on your comments I figured out the issues I was having.

If I have further operational/methodology questions (as opposed to build
issues and runtime errors) is this an appropriate forum to raise them?

**Comment by jbscoggi** [comment]
Glad to hear you figured it out.  Yes, if you have any other questions, please fill another issue.  Thanks!
