### ISSUE TITLE
error trying the 'pip install .... mutationpp' command 

### ISSUE THREAD

**Issue by anfuso1193** [mutationpp/Mutationpp#170]
Hi,
I am currently trying to install the new python package to directly work with mutation++. 
However, here is attached a link with the errors I am facing. I am using a MacBook with Mojave (version 10.14.6) and Python 3.9.6

<img width="1440" alt="mpp" src="https://user-images.githubusercontent.com/8077364/127033028-81311f3a-5442-466e-9a42-4f81f2fc2beb.png">

I know it is a new feature so let me know if you need any additional details. Thanks!!

**Comment by rubendibattista** [comment]
Hello, thanks for reporting this. I edited your message to put your image directly in the message to avoid broken links in the future. It's a good practice to put everything in a issue message. 

Now, to the problem. The problem arises because we'are currently building pre-built wheels only for Catalina, so on Mojave you need to build the source distribution from scratch. So the easiest fix would be to update your OS if you can. 

If you can't I have some questions for you:
- Are you running the install inside a virtualenv? 
- Which version of pip and python are you using?

**Comment by anfuso1193** [comment]
Thanks Ruben, I uploaded to Catalina and the installation was successful.
Thanks for your help.

Cheers,
Enrico!
