### ISSUE TITLE
Air-Camphor GSI for Low-Temperature Ablator

### ISSUE THREAD

**Issue by aobaskaya** [mutationpp/Mutationpp#242]
I would like to have ablation of Camphor ( C10H16O ), without gas reactions, so for a low-temperature ablator simulation.
I would like to have 2 species, air and camphor, and the sublimation of camphor as the ablation mechanism.
Could this be handled by Mutation++?

Thank you all in advance!

**Comment by BBArrosDias** [comment]
Yes. You can check the sublimation reaction in the GSI model. You need at least two species for air.

**Comment by mgoodson-cvd** [comment]
@BBArrosDias is correct, `Air` won't work as a species (although it does have an entry in the NASA-9 database). And the sublimation reaction model is available in GSI.

To further clarify, Mutation++ does not currently include any entries for `C10H16O` in its databases, so you will need to provide the thermo and transport properties for camphor by modifying the databases. I know there is some data available for camphor in literature from VKI and University of Kentucky.

**Comment by aobaskaya** [comment]
Then, @mgoodson-cvd , I would have 3 species with N2, O2, and C10H16O, that should work.

For sublimation, I know that the current input expects an Arrhenius equation form, whereas the vapor pressure I find for camphor are in Antoine equation form. But I guess that also shouldn't be a big issue, just a one line addition maybe.

For the databases: Then, I should add the NASA polynomial information for camphor in, for example, nasa9.dat in the data folder.

I think it is less straightforward for transport. I see some information about the input files, but could you tell me a bit about how I could do this for my setup with the above mixture?

**Comment by mgoodson-cvd** [comment]
Yes, the GSI sublimation reaction can be modified. Correct on adding the NASA-9. You'll need to add camphor to species.xml as well so that it can compute the molecular weight correctly.

For the transport, not as straightforward. You'll need collision integrals for each species and camphor, e.g.,
```
<pair s1="C10H16O" s2="N2">
```
Not sure if any of those are published yet unfortunately. The Zibitsker papers from 2022 make note of them but only give the resultant curve fits.

**Comment by BBArrosDias** [comment]
For transport, Aelx used the Pirani potential, so you don't need the collision integrals. He asked someone at Ames to compute these properties. If you want go to know more check this paper:
https://web.archive.org/web/20220806113753id_/https://aip.scitation.org/doi/pdf/10.1063/5.0098060
For sublimation, you can just fit Antoine law into Arrhenius.

**Comment by BBArrosDias** [comment]
Hi @aobaskaya, here are the Pirani potential parameters for camphor that Justin Haskins and George have computed based on the paper above. Please remember to cite the paper it if you use this data!
    
<dipole-polarizabilities units="Å-Å-Å">
        <species name="C16H10O"      value=" 16.5336"/>
    </dipole-polarizabilities>
 
    <effective-electrons>
        <species name=" C16H10O"      value=" 17.046"/>
    </effective-electrons>

In the future, it would be better to move these topics into the discussion section instead of the issues.
Best of luck!

**Comment by aobaskaya** [comment]
Thank you so much for this! I will add these.
