### ISSUE TITLE
Reaction Classification update

### ISSUE THREAD

**Issue by grgbellasvki** [mutationpp/Mutationpp#30]
Update the classification properties according to the work of 
Julien Amorosseti.

Check the reaction classification test.

**Comment by amorosej** [comment]
Here is a proposal:

I use 5 types of tests. 
- The first is the number of electrons in products minus that in reactants : if positive, it is the branch of ionization/detachment, if negative ion recombination/attachment, if zero dissociation/recombination/(de-)excitation/exchange.
- For the first and second branch, to distinguish between ionization (resp. ion recombination) and detachment (resp. attachment), I check the sum of abs(charge) of heavy species in products minus that in reactants. If positive, you have ionization, if negative, detachment. Example : O + M = O+ + e- + M (ionization) and O- + M = O + e- + M (detachment). The abs() is the key here. The remaining tests on these branches allow to identify heavy particle impact or electron impact or associative/dissociative processes.
- For the third branch, we check the number of products minus the number of reactants : if positive, it is the branch of dissociation, if negative recombination, if zero (de-)excitation or exchange. The remaining tests are straightforward. Note that:
1) I grouped neutral exchange (e.g.. N2+O=NO+N), charge exchange (e.g. N2+N+=N2++N) and generalized exchange (e.g. N2+O+=NO+N+) in a "exchange" category, since there is no need to distinguish between them. However, if one wants to split it, it can still be done.
2) Excitation and deexcitation are also grouped.
3) For use in state-to-state, the third branch can be easily extended without rewriting it, so that the various types of excitation reaction (rotational, vibrational, electronic) are differentiated.

The labels in the diagram are:
I = ionization ; Det = detachment ; AI = associative ionization ; ADet = associative detachment ; IR = ion recombination ; Att = attachment ; DR = dissociative recombination ; DAtt = dissociative attachment ; D = dissociation ; R = recombination ; E = (de-)excitation.
h stands for heavy particle impact process, e stands for electron impact process.

I put the modified src files that I use with the above tree. I could extend the ctest for this tree ; there would be then concrete examples of reactions of each type in it.
[reaction_tree.zip](https://github.com/mutationpp/Mutationpp/files/2918971/reaction_tree.zip)

**Comment by jbscoggi** [comment]
This issue was solved in #42. Closing.
