### ISSUE TITLE
Build error on Fedora 28, gcc 8.3.1: libmutation++.so not found

### ISSUE THREAD

**Issue by gbogopolsky** [mutationpp/Mutationpp#87]
On Fedora 28, while building with gcc 8.3.1 20190223 (Red Had 8.3.1-2), `checkmix` and `mppequil` return the following error on execution:
`checkmix: error while loading shared libraries: libmutation++.so: cannot open shared object file: No such file or directory`.

Comparing to a working build on Ubuntu 18.04, gcc-7, I notice that `libmutation++.so` is found in `Mutationpp/install/lib` whereas it is found in `Mutationpp/install/lib64` on Fedora. Renaming it `Mutationpp/install/lib` solves the issue (but building anew creates a new `lib64` folder).

**Note:** All the test are passing without modifying the directory.

I do not know a lot about cmake yet, so I unfortunately cannot contribute more to this issue...

**Comment by rubendibattista** [comment]
The correct lib path on RHEL distros is automatically retrieved by cmake to
be <install_prefix>/lib64. It should also be automatically linked for the
executables.

Did you clean up your previous builds? Did you start the build from scratch?

Can you list all the steps you take to produce the error?

**Comment by gbogopolsky** [comment]
Thanks for the info, I didn't know that.

I start the build from scratch (a fresh git clone), following the prescribed steps from [here](https://github.com/mutationpp/Mutationpp/blob/master/docs/installation.md#top),
ie the following steps:
- Set the exports in `.bahsrc`
- `mkdir build`
- `cmake -DCMAKE_INSTALL_PREFIX:PATH=$(realpath ../install) ..`
- `make -j 4 install`

Redoing the steps made me notice that there is a difference in the LD_LIBRARY_PATH export for Linux: `export LD_LIBRARY_PATH=$MPP_DIRECTORY/install/lib:$LD_LIBRARY_PATH`, and not `lib64`.
Changing it solves the issue.

Is there a way for the export to be distribution independent or should we consider this issue closed?

**Comment by rubendibattista** [comment]
Exactly, the solution is to correctly export the right `LD_LIBRARY_PATH`
(on Linux).

The current behavior is the standard one. Because by default a library gets
installed in the system prefix (normally `/usr/local`) plus the "LIBDIR".
On RHEL based distros the library path for x86_64 libraries is `lib64` and
not `lib`, and the operaring system is instructed to look for them there
(even if there are some quirks). That's why we use the standard way of
doing things.

Just FYI, this is automatically handled by cmake GNUInstallDirs.
https://cmake.org/cmake/help/v3.15/module/GNUInstallDirs.html

So I think we can close this issue. ☺

**Comment by gbogopolsky** [comment]
Thanks a lot for your explanation.

Maybe adding a line in the instruction installation for RHEL based distributions?
