### ISSUE TITLE
Merging GSI to main mutation 

### ISSUE THREAD

**Issue by grgbellasvki** [mutationpp/Mutationpp#9]

**Comment by lkampoli** [comment]
Hello,
in this regards, I previously mentioned that when I try to interface COOLFluiD with the present version of Mutationpp, the compilation `make` goes ok but running any testcase raises an error, which seems due to the fact that some file is not correctly found/read in the database for the GSI module.
Indeed, recompiling the library without GSI, solved the issue for me.

[error.log](https://github.com/mutationpp/Mutationpp/files/3062930/error.log)

Kind regards,
Lorenzo

**Comment by grgbellasvki** [comment]
I will look into it. Thanks for post.

**Comment by jbscoggi** [comment]
Solved by #22. Closing.
